/*
    Author: Clinton Daniel
    Description: Demonstrating JavaScript
    Date: 11/10/2024
*/

function myUSF(){
    document.getElementById("my6225").innerHTML = "This is my First ISM6225 Data example."
}

// Now we know how to execute an external JavaScript.
function MickeyMouse(){
    document.getElementById("demo").innerHTML = "May The Force Be With You!";
}

// This demonstrates the use of variables. 
function LearningVariables(){
    var a = 5;
    var b = 6;
    var c = a + b;
    // The + sign here is used to concatenate a string
    document.getElementById("CalcVar").innerHTML = "The value of c is: " + c + " and it was generated by JavaScript.";
}

function DemoArrays(){
    const myclass = ["Distributed Information Systems", "Advanced Database Management", "Information Security Risk Management"];
    let classlength = myclass.length;

    let text = "<ul>";
    for (let i =0; i < classlength; i++)
    {
        text += "<li>" + myclass[i] + "</li>";
        document.getElementById("MyList").innerHTML = text;
    }
    text += "</ul>";

}

function AboutAmerAwad(){
    document.getElementById("ameraboutme").innerHTML = "Amer Awad is a graduate student at the University of South Florida working towards his MS in AI and Business Analytics. While Amer does currently work at a tax software company, he does not deal with building websites; this is his first foray into that area. For the creation of this website, Amer used the tools provided my Dr. Clinton Daniel, his professor for his Application Development class, along with VSCode and GitHub (https://github.com/amerwawad).";
}

function starwarsbikeriders(){
    document.getElementById("swbikes").innerHTML = "Select the Star Wars character and the bicycle you think go together!";
}